# Generated by Django 6.0.5 on 2026-05-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomenclature',
            name='is_active',
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
