# Generated by Django 6.0.6 on 2026-06-04 09:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_nomenclature_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclature',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Ціна не може бути меншою або дорівнювати 0')]),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Ціна не може бути меншою або дорівнювати 0')]),
        ),
    ]
