# Generated by Django 6.0.6 on 2026-06-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_nomenclature_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='type',
            field=models.CharField(choices=[('product', 'Товар'), ('service', 'Послуга')], default='product', max_length=20),
        ),
    ]
