# Generated by Django 6.0.5 on 2026-06-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_nomenclature_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='base_currency',
            field=models.CharField(choices=[('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
