# Generated by Django 6.0.5 on 2026-05-27 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('warehouses', '0002_alter_servicejob_customer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashregister',
            name='warehouse_name',
        ),
        migrations.AddField(
            model_name='cashregister',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='warehouses.warehouse'),
            preserve_default=False,
        ),
    ]
