# Generated by Django 6.0.5 on 2026-05-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_cashregister_warehouse_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
