# Generated by Django 6.0.5 on 2026-06-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status_alter_orderitem_quantity'),
        ('orders', '0007_alter_order_total_amount'),
    ]

    operations = [
    ]
