# Generated by Django 6.0.6 on 2026-06-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_merge_20260604_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR')], default='UAH', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_uah',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
