# Generated by Django 6.0.6 on 2026-06-07 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_counterparty_order_counterparty'),
        ('warehouses', '0013_servicejob_counterparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.counterparty'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='warehouses.servicejob'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Виконано'), ('pending', 'Очікує оплати')], default='completed', max_length=20),
        ),
    ]
