# Generated by Django 6.0.6 on 2026-06-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_transaction_counterparty_transaction_service_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('prepay', 'Передоплата'), ('payment', 'Оплата'), ('refund', 'Повернення коштів'), ('sale', 'Продаж'), ('income', 'Внесення'), ('expense', 'Видача'), ('return', 'Повернення товару'), ('debt', 'Борг')], max_length=20),
        ),
    ]
