# Generated by Django 6.0.6 on 2026-06-07 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_transaction_transaction_type'),
        ('warehouses', '0013_servicejob_counterparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='related_retail_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backorder_purchases', to='orders.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='related_service_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backorder_purchases', to='warehouses.servicejob'),
        ),
    ]
