# Generated by Django 6.0.5 on 2026-05-27 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicejob',
            name='customer_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Номер телефону має бути у форматі: '+380991234567'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='servicejob',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AddConstraint(
            model_name='servicejob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'in_progress'])), fields=('storage_cell',), name='unique_active_cell'),
        ),
    ]
