# Generated by Django 6.0.5 on 2026-05-29 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('warehouses', '0003_warehousestock'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='servicejob',
            name='unique_active_cell',
        ),
        migrations.AddField(
            model_name='servicejob',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicejob',
            name='status',
            field=models.CharField(choices=[('pending', 'Прийнято'), ('waiting_parts', 'Очікує компонентів'), ('done', 'Відремонтовано'), ('returned', 'Видано')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_stocks', to='products.nomenclature'),
        ),
        migrations.AddConstraint(
            model_name='servicejob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'waiting_parts']), ('is_archived', False)), fields=('storage_cell',), name='unique_active_cell'),
        ),
    ]
