# Generated by Django 6.0.5 on 2026-05-30 16:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0004_remove_servicejob_unique_active_cell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicejob',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
