# Generated by Django 6.0.5 on 2026-06-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0005_servicejob_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicejob',
            name='storage_cell',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
