# Generated by Django 6.0.6 on 2026-06-04 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_supplier_order_supplier'),
        ('products', '0004_alter_nomenclature_purchase_price_and_more'),
        ('warehouses', '0006_alter_servicejob_storage_cell'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField()),
                ('quantity_before', models.IntegerField()),
                ('quantity_after', models.IntegerField()),
                ('reason', models.CharField(choices=[('sale', 'Продаж'), ('purchase', 'Закупівля'), ('return', 'Повернення'), ('correction', 'Коригування')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='products.nomenclature')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='warehouses.warehouse')),
            ],
        ),
    ]
