# Generated by Django 6.0.6 on 2026-06-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0007_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousestock',
            name='reserved_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
