# Generated by Django 6.0.6 on 2026-06-06 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0008_warehousestock_reserved_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='transfer_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_movements', to='warehouses.warehouse'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('sale', 'Продаж'), ('purchase', 'Закупівля'), ('return', 'Повернення'), ('correction', 'Коригування'), ('transfer', 'Переміщення')], max_length=20),
        ),
    ]
