# Generated by Django 6.0.5 on 2026-06-06 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_nomenclature_base_currency_nomenclature_base_price'),
        ('warehouses', '0009_stockmovement_transfer_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicejob',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_jobs', to='products.nomenclature'),
        ),
    ]
