# Generated by Django 6.0.5 on 2026-06-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0010_servicejob_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicejob',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
