# Generated by Django 6.0.5 on 2026-06-07 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_currency_transaction_amount_uah'),
        ('warehouses', '0011_servicejob_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicejob',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='cash_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_jobs', to='orders.cashregister'),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='payment_currency',
            field=models.CharField(choices=[('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR')], default='UAH', max_length=3),
        ),
        migrations.AddField(
            model_name='servicejob',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Не оплачено'), ('partial', 'Частково'), ('paid', 'Оплачено')], default='unpaid', max_length=10),
        ),
    ]
